/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiMobileWalletsRouteImport } from './routes/api/mobile/wallets'
import { Route as ApiMobileTransactionsRouteImport } from './routes/api/mobile/transactions'
import { Route as ApiMobileGoalsRouteImport } from './routes/api/mobile/goals'
import { Route as ApiMobileDashboardRouteImport } from './routes/api/mobile/dashboard'
import { Route as ApiMobileCategoriesRouteImport } from './routes/api/mobile/categories'
import { Route as ApiMobileBudgetsRouteImport } from './routes/api/mobile/budgets'
import { Route as ApiMobileAnalyticsRouteImport } from './routes/api/mobile/analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMobileWalletsTransferRouteImport } from './routes/api/mobile/wallets.transfer'
import { Route as ApiMobileWalletsIdRouteImport } from './routes/api/mobile/wallets.$id'
import { Route as ApiMobileTransactionsTriggerRecurringRouteImport } from './routes/api/mobile/transactions.trigger-recurring'
import { Route as ApiMobileTransactionsMaxDateRouteImport } from './routes/api/mobile/transactions.max-date'
import { Route as ApiMobileTransactionsIdRouteImport } from './routes/api/mobile/transactions.$id'
import { Route as ApiMobileGoalsIdRouteImport } from './routes/api/mobile/goals.$id'
import { Route as ApiMobileBudgetsIdRouteImport } from './routes/api/mobile/budgets.$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiMobileWalletsRoute = ApiMobileWalletsRouteImport.update({
  id: '/api/mobile/wallets',
  path: '/api/mobile/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTransactionsRoute = ApiMobileTransactionsRouteImport.update({
  id: '/api/mobile/transactions',
  path: '/api/mobile/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileGoalsRoute = ApiMobileGoalsRouteImport.update({
  id: '/api/mobile/goals',
  path: '/api/mobile/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileDashboardRoute = ApiMobileDashboardRouteImport.update({
  id: '/api/mobile/dashboard',
  path: '/api/mobile/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileCategoriesRoute = ApiMobileCategoriesRouteImport.update({
  id: '/api/mobile/categories',
  path: '/api/mobile/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileBudgetsRoute = ApiMobileBudgetsRouteImport.update({
  id: '/api/mobile/budgets',
  path: '/api/mobile/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAnalyticsRoute = ApiMobileAnalyticsRouteImport.update({
  id: '/api/mobile/analytics',
  path: '/api/mobile/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileWalletsTransferRoute =
  ApiMobileWalletsTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => ApiMobileWalletsRoute,
  } as any)
const ApiMobileWalletsIdRoute = ApiMobileWalletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileWalletsRoute,
} as any)
const ApiMobileTransactionsTriggerRecurringRoute =
  ApiMobileTransactionsTriggerRecurringRouteImport.update({
    id: '/trigger-recurring',
    path: '/trigger-recurring',
    getParentRoute: () => ApiMobileTransactionsRoute,
  } as any)
const ApiMobileTransactionsMaxDateRoute =
  ApiMobileTransactionsMaxDateRouteImport.update({
    id: '/max-date',
    path: '/max-date',
    getParentRoute: () => ApiMobileTransactionsRoute,
  } as any)
const ApiMobileTransactionsIdRoute = ApiMobileTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileTransactionsRoute,
} as any)
const ApiMobileGoalsIdRoute = ApiMobileGoalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileGoalsRoute,
} as any)
const ApiMobileBudgetsIdRoute = ApiMobileBudgetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMobileBudgetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/analytics': typeof ApiMobileAnalyticsRoute
  '/api/mobile/budgets': typeof ApiMobileBudgetsRouteWithChildren
  '/api/mobile/categories': typeof ApiMobileCategoriesRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/goals': typeof ApiMobileGoalsRouteWithChildren
  '/api/mobile/transactions': typeof ApiMobileTransactionsRouteWithChildren
  '/api/mobile/wallets': typeof ApiMobileWalletsRouteWithChildren
  '/api/mobile/budgets/$id': typeof ApiMobileBudgetsIdRoute
  '/api/mobile/goals/$id': typeof ApiMobileGoalsIdRoute
  '/api/mobile/transactions/$id': typeof ApiMobileTransactionsIdRoute
  '/api/mobile/transactions/max-date': typeof ApiMobileTransactionsMaxDateRoute
  '/api/mobile/transactions/trigger-recurring': typeof ApiMobileTransactionsTriggerRecurringRoute
  '/api/mobile/wallets/$id': typeof ApiMobileWalletsIdRoute
  '/api/mobile/wallets/transfer': typeof ApiMobileWalletsTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/analytics': typeof ApiMobileAnalyticsRoute
  '/api/mobile/budgets': typeof ApiMobileBudgetsRouteWithChildren
  '/api/mobile/categories': typeof ApiMobileCategoriesRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/goals': typeof ApiMobileGoalsRouteWithChildren
  '/api/mobile/transactions': typeof ApiMobileTransactionsRouteWithChildren
  '/api/mobile/wallets': typeof ApiMobileWalletsRouteWithChildren
  '/api/mobile/budgets/$id': typeof ApiMobileBudgetsIdRoute
  '/api/mobile/goals/$id': typeof ApiMobileGoalsIdRoute
  '/api/mobile/transactions/$id': typeof ApiMobileTransactionsIdRoute
  '/api/mobile/transactions/max-date': typeof ApiMobileTransactionsMaxDateRoute
  '/api/mobile/transactions/trigger-recurring': typeof ApiMobileTransactionsTriggerRecurringRoute
  '/api/mobile/wallets/$id': typeof ApiMobileWalletsIdRoute
  '/api/mobile/wallets/transfer': typeof ApiMobileWalletsTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mobile/analytics': typeof ApiMobileAnalyticsRoute
  '/api/mobile/budgets': typeof ApiMobileBudgetsRouteWithChildren
  '/api/mobile/categories': typeof ApiMobileCategoriesRoute
  '/api/mobile/dashboard': typeof ApiMobileDashboardRoute
  '/api/mobile/goals': typeof ApiMobileGoalsRouteWithChildren
  '/api/mobile/transactions': typeof ApiMobileTransactionsRouteWithChildren
  '/api/mobile/wallets': typeof ApiMobileWalletsRouteWithChildren
  '/api/mobile/budgets/$id': typeof ApiMobileBudgetsIdRoute
  '/api/mobile/goals/$id': typeof ApiMobileGoalsIdRoute
  '/api/mobile/transactions/$id': typeof ApiMobileTransactionsIdRoute
  '/api/mobile/transactions/max-date': typeof ApiMobileTransactionsMaxDateRoute
  '/api/mobile/transactions/trigger-recurring': typeof ApiMobileTransactionsTriggerRecurringRoute
  '/api/mobile/wallets/$id': typeof ApiMobileWalletsIdRoute
  '/api/mobile/wallets/transfer': typeof ApiMobileWalletsTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/analytics'
    | '/dashboard'
    | '/goals'
    | '/transactions'
    | '/wallets'
    | '/api/auth/$'
    | '/api/mobile/analytics'
    | '/api/mobile/budgets'
    | '/api/mobile/categories'
    | '/api/mobile/dashboard'
    | '/api/mobile/goals'
    | '/api/mobile/transactions'
    | '/api/mobile/wallets'
    | '/api/mobile/budgets/$id'
    | '/api/mobile/goals/$id'
    | '/api/mobile/transactions/$id'
    | '/api/mobile/transactions/max-date'
    | '/api/mobile/transactions/trigger-recurring'
    | '/api/mobile/wallets/$id'
    | '/api/mobile/wallets/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/analytics'
    | '/dashboard'
    | '/goals'
    | '/transactions'
    | '/wallets'
    | '/api/auth/$'
    | '/api/mobile/analytics'
    | '/api/mobile/budgets'
    | '/api/mobile/categories'
    | '/api/mobile/dashboard'
    | '/api/mobile/goals'
    | '/api/mobile/transactions'
    | '/api/mobile/wallets'
    | '/api/mobile/budgets/$id'
    | '/api/mobile/goals/$id'
    | '/api/mobile/transactions/$id'
    | '/api/mobile/transactions/max-date'
    | '/api/mobile/transactions/trigger-recurring'
    | '/api/mobile/wallets/$id'
    | '/api/mobile/wallets/transfer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/transactions'
    | '/_authenticated/wallets'
    | '/api/auth/$'
    | '/api/mobile/analytics'
    | '/api/mobile/budgets'
    | '/api/mobile/categories'
    | '/api/mobile/dashboard'
    | '/api/mobile/goals'
    | '/api/mobile/transactions'
    | '/api/mobile/wallets'
    | '/api/mobile/budgets/$id'
    | '/api/mobile/goals/$id'
    | '/api/mobile/transactions/$id'
    | '/api/mobile/transactions/max-date'
    | '/api/mobile/transactions/trigger-recurring'
    | '/api/mobile/wallets/$id'
    | '/api/mobile/wallets/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMobileAnalyticsRoute: typeof ApiMobileAnalyticsRoute
  ApiMobileBudgetsRoute: typeof ApiMobileBudgetsRouteWithChildren
  ApiMobileCategoriesRoute: typeof ApiMobileCategoriesRoute
  ApiMobileDashboardRoute: typeof ApiMobileDashboardRoute
  ApiMobileGoalsRoute: typeof ApiMobileGoalsRouteWithChildren
  ApiMobileTransactionsRoute: typeof ApiMobileTransactionsRouteWithChildren
  ApiMobileWalletsRoute: typeof ApiMobileWalletsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/mobile/wallets': {
      id: '/api/mobile/wallets'
      path: '/api/mobile/wallets'
      fullPath: '/api/mobile/wallets'
      preLoaderRoute: typeof ApiMobileWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/transactions': {
      id: '/api/mobile/transactions'
      path: '/api/mobile/transactions'
      fullPath: '/api/mobile/transactions'
      preLoaderRoute: typeof ApiMobileTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/goals': {
      id: '/api/mobile/goals'
      path: '/api/mobile/goals'
      fullPath: '/api/mobile/goals'
      preLoaderRoute: typeof ApiMobileGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/dashboard': {
      id: '/api/mobile/dashboard'
      path: '/api/mobile/dashboard'
      fullPath: '/api/mobile/dashboard'
      preLoaderRoute: typeof ApiMobileDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/categories': {
      id: '/api/mobile/categories'
      path: '/api/mobile/categories'
      fullPath: '/api/mobile/categories'
      preLoaderRoute: typeof ApiMobileCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/budgets': {
      id: '/api/mobile/budgets'
      path: '/api/mobile/budgets'
      fullPath: '/api/mobile/budgets'
      preLoaderRoute: typeof ApiMobileBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/analytics': {
      id: '/api/mobile/analytics'
      path: '/api/mobile/analytics'
      fullPath: '/api/mobile/analytics'
      preLoaderRoute: typeof ApiMobileAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/wallets/transfer': {
      id: '/api/mobile/wallets/transfer'
      path: '/transfer'
      fullPath: '/api/mobile/wallets/transfer'
      preLoaderRoute: typeof ApiMobileWalletsTransferRouteImport
      parentRoute: typeof ApiMobileWalletsRoute
    }
    '/api/mobile/wallets/$id': {
      id: '/api/mobile/wallets/$id'
      path: '/$id'
      fullPath: '/api/mobile/wallets/$id'
      preLoaderRoute: typeof ApiMobileWalletsIdRouteImport
      parentRoute: typeof ApiMobileWalletsRoute
    }
    '/api/mobile/transactions/trigger-recurring': {
      id: '/api/mobile/transactions/trigger-recurring'
      path: '/trigger-recurring'
      fullPath: '/api/mobile/transactions/trigger-recurring'
      preLoaderRoute: typeof ApiMobileTransactionsTriggerRecurringRouteImport
      parentRoute: typeof ApiMobileTransactionsRoute
    }
    '/api/mobile/transactions/max-date': {
      id: '/api/mobile/transactions/max-date'
      path: '/max-date'
      fullPath: '/api/mobile/transactions/max-date'
      preLoaderRoute: typeof ApiMobileTransactionsMaxDateRouteImport
      parentRoute: typeof ApiMobileTransactionsRoute
    }
    '/api/mobile/transactions/$id': {
      id: '/api/mobile/transactions/$id'
      path: '/$id'
      fullPath: '/api/mobile/transactions/$id'
      preLoaderRoute: typeof ApiMobileTransactionsIdRouteImport
      parentRoute: typeof ApiMobileTransactionsRoute
    }
    '/api/mobile/goals/$id': {
      id: '/api/mobile/goals/$id'
      path: '/$id'
      fullPath: '/api/mobile/goals/$id'
      preLoaderRoute: typeof ApiMobileGoalsIdRouteImport
      parentRoute: typeof ApiMobileGoalsRoute
    }
    '/api/mobile/budgets/$id': {
      id: '/api/mobile/budgets/$id'
      path: '/$id'
      fullPath: '/api/mobile/budgets/$id'
      preLoaderRoute: typeof ApiMobileBudgetsIdRouteImport
      parentRoute: typeof ApiMobileBudgetsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiMobileBudgetsRouteChildren {
  ApiMobileBudgetsIdRoute: typeof ApiMobileBudgetsIdRoute
}

const ApiMobileBudgetsRouteChildren: ApiMobileBudgetsRouteChildren = {
  ApiMobileBudgetsIdRoute: ApiMobileBudgetsIdRoute,
}

const ApiMobileBudgetsRouteWithChildren =
  ApiMobileBudgetsRoute._addFileChildren(ApiMobileBudgetsRouteChildren)

interface ApiMobileGoalsRouteChildren {
  ApiMobileGoalsIdRoute: typeof ApiMobileGoalsIdRoute
}

const ApiMobileGoalsRouteChildren: ApiMobileGoalsRouteChildren = {
  ApiMobileGoalsIdRoute: ApiMobileGoalsIdRoute,
}

const ApiMobileGoalsRouteWithChildren = ApiMobileGoalsRoute._addFileChildren(
  ApiMobileGoalsRouteChildren,
)

interface ApiMobileTransactionsRouteChildren {
  ApiMobileTransactionsIdRoute: typeof ApiMobileTransactionsIdRoute
  ApiMobileTransactionsMaxDateRoute: typeof ApiMobileTransactionsMaxDateRoute
  ApiMobileTransactionsTriggerRecurringRoute: typeof ApiMobileTransactionsTriggerRecurringRoute
}

const ApiMobileTransactionsRouteChildren: ApiMobileTransactionsRouteChildren = {
  ApiMobileTransactionsIdRoute: ApiMobileTransactionsIdRoute,
  ApiMobileTransactionsMaxDateRoute: ApiMobileTransactionsMaxDateRoute,
  ApiMobileTransactionsTriggerRecurringRoute:
    ApiMobileTransactionsTriggerRecurringRoute,
}

const ApiMobileTransactionsRouteWithChildren =
  ApiMobileTransactionsRoute._addFileChildren(
    ApiMobileTransactionsRouteChildren,
  )

interface ApiMobileWalletsRouteChildren {
  ApiMobileWalletsIdRoute: typeof ApiMobileWalletsIdRoute
  ApiMobileWalletsTransferRoute: typeof ApiMobileWalletsTransferRoute
}

const ApiMobileWalletsRouteChildren: ApiMobileWalletsRouteChildren = {
  ApiMobileWalletsIdRoute: ApiMobileWalletsIdRoute,
  ApiMobileWalletsTransferRoute: ApiMobileWalletsTransferRoute,
}

const ApiMobileWalletsRouteWithChildren =
  ApiMobileWalletsRoute._addFileChildren(ApiMobileWalletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMobileAnalyticsRoute: ApiMobileAnalyticsRoute,
  ApiMobileBudgetsRoute: ApiMobileBudgetsRouteWithChildren,
  ApiMobileCategoriesRoute: ApiMobileCategoriesRoute,
  ApiMobileDashboardRoute: ApiMobileDashboardRoute,
  ApiMobileGoalsRoute: ApiMobileGoalsRouteWithChildren,
  ApiMobileTransactionsRoute: ApiMobileTransactionsRouteWithChildren,
  ApiMobileWalletsRoute: ApiMobileWalletsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
